const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.goto(process.env.CLIMB_TEST_URL||pathToFileURL(path.resolve(__dirname,'../index.html')).href);
    await page.waitForFunction(()=>window.CostModel&&window.climbAnimation);
    const total=()=>page.locator('#budget-total').textContent();
    assert.equal(await total(),'€2,195.57');
    assert.equal(await page.locator('#component-rows tr').count(),14);
    await page.locator('[data-price="delivery"]').fill('100');
    await page.locator('#preset-retail').click();
    assert.equal(await page.locator('[data-price="delivery"]').inputValue(),'100','Preset must preserve custom transport');
    assert.equal(await total(),'€2,462.30');
    await page.locator('#budget-reset').click();
    await page.locator('#budget-panels').fill('5');
    assert.equal(await page.locator('[data-component="plywood"] .component-quantity').textContent(),'3');
    assert.equal(await page.locator('[data-component="tnuts"] .component-quantity').textContent(),'3');
    await page.locator('#budget-holds').fill('60');
    await page.locator('#use-best-holds').click();
    assert.equal(await page.locator('#budget-pack').inputValue(),'100');
    assert.equal(await page.locator('[data-component="holds"] .component-total').textContent(),'€249.95');
    assert.match(await page.locator('#budget-facts').textContent(),/100 holds purchased \/ 60 installed/);
    await page.locator('[data-price="cnc"]').fill('50');
    const customTotal=await total();await page.reload();
    assert.equal(await total(),customTotal,'Inputs must survive reload');
    await page.locator('[data-price="plywood"]').fill('');
    assert.equal(await total(),'—');assert.equal(await page.locator('#budget-error').isVisible(),true);
    await page.locator('#budget-reset').click();
    await page.locator('#quote-goods').fill('200');await page.locator('#quote-freight').fill('50');
    assert.match(await page.locator('#quote-result').textContent(),/€250.00 delivered/);
    await page.locator('[data-price="delivery"]').fill('500');
    assert.match(await page.locator('#quote-result').textContent(),/current option €690.96/,'Quote comparison must follow budget delivery changes');
    await page.locator('#quote-local-freight').fill('20');
    await page.locator('[data-price="delivery"]').fill('600');
    assert.match(await page.locator('#quote-result').textContent(),/current option €210.96/,'Explicit delivery allocation must be preserved');
    assert.match(await page.locator('#quote-requirement').textContent(),/custom delivery allocation/);
    await page.locator('#quote-origin').selectOption('import');
    assert.match(await page.locator('#quote-result').textContent(),/Enter the full order/);
    await page.locator('#quote-goods').fill('200');await page.locator('#quote-freight').fill('100');
    await page.locator('#quote-duty').fill('30');await page.locator('#quote-fees').fill('15');
    assert.match(await page.locator('#quote-result').textContent(),/€414.30 delivered/);
    assert.match(await page.locator('#quote-result').textContent(),/€69.30 import VAT/);
    await page.locator('#quote-quantity').fill('1');
    assert.match(await page.locator('#quote-result').textContent(),/enough units/);
    await page.locator('#quote-component').selectOption('matting');
    assert.equal(await page.locator('#quote-goods').inputValue(),'','Do not reuse plywood quote for matting');
    assert.equal(await page.locator('#quote-local-freight').inputValue(),'150');
    await page.locator('#budget-reset').click();
    await page.locator('#budget').scrollIntoViewIfNeeded();
    await page.evaluate(()=>document.getElementById('budget').scrollIntoView());
    await page.screenshot({path:path.join(__dirname,'budget-desktop.png')});
    await page.locator('#savings-title').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(__dirname,'sourcing-desktop.png')});
    await page.setViewportSize({width:390,height:844});
    await page.locator('#budget').screenshot({path:path.join(__dirname,'budget-mobile.png')});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile must fit horizontally');
    assert.deepEqual(errors,[]);
    console.log('PASS: EUR totals, editable prices, pack rounding, bulk comparison, persistence, input validation, transport preservation, EU/import quotes, quote scope, mobile layout; no browser errors.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
